// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfL4pVtcHVL8d-M5UDpxIL_V34Fe20rl4',
    appId: '1:777352501830:web:a402de5ea2458a76d10847',
    messagingSenderId: '777352501830',
    projectId: 'gdscnotes',
    authDomain: 'gdscnotes.firebaseapp.com',
    storageBucket: 'gdscnotes.appspot.com',
    measurementId: 'G-G76Z4WP3W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuGymp9AjKBgYP8sp7TVnWZ6xyAQfTbk',
    appId: '1:777352501830:android:a1dbdf431640b5e6d10847',
    messagingSenderId: '777352501830',
    projectId: 'gdscnotes',
    storageBucket: 'gdscnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErw5k1-T2sUS63SoigmbYdjzK0e7gVmI',
    appId: '1:777352501830:ios:95bc104174e41524d10847',
    messagingSenderId: '777352501830',
    projectId: 'gdscnotes',
    storageBucket: 'gdscnotes.appspot.com',
    iosBundleId: 'com.gdsc.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErw5k1-T2sUS63SoigmbYdjzK0e7gVmI',
    appId: '1:777352501830:ios:8edfbbf9ff83e132d10847',
    messagingSenderId: '777352501830',
    projectId: 'gdscnotes',
    storageBucket: 'gdscnotes.appspot.com',
    iosBundleId: 'com.gdsc.myNotes.RunnerTests',
  );
}
